"""The homed preprint build (Session 55, D55): front matter, manuscript assembly, footnote reuse.

The PDF step (pandoc + WeasyPrint) is not exercised here — CI builds no PDF — but the pure pieces
are: the footnote merge/renumber, the manuscript title-block transform, and the front-matter config.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from schelling.preprint.frontmatter import FrontMatter, load_front_matter
from schelling.preprint.manuscript import assemble_manuscript
from schelling.preprint.pdf import inline_figures, reuse_footnotes

REPO = Path(__file__).resolve().parent.parent


def _fm() -> FrontMatter:
    return FrontMatter(
        author="A. Author",
        affiliation="Somewhere",
        contact="a@x.org",
        orcid="0009-0004-5391-4030",
        dateline="Preprint · 2026-01-01 · v9",
        runhead="Head",
        keywords="one; two",
        version_note="changed things",
    )


# ------------------------------------------------------------ footnote merge/renumber (item 2)
def test_reuse_footnotes_merges_duplicates_and_renumbers_to_canonical() -> None:
    """Pandoc renders a re-used footnote as a duplicate note; reuse_footnotes merges by content and
    renumbers so both citations point at — and display — one canonical number (the D54/D55 core)."""
    html = (
        '<p>First<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> '  # noqa: E501
        'other<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> '
        'again<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>.</p>'  # noqa: E501
        '<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">'
        "<hr /><ol>"
        '<li id="fn1"><p>NOTE A<a href="#fnref1" class="footnote-back">back</a></p></li>'
        '<li id="fn2"><p>NOTE B<a href="#fnref2" class="footnote-back">back</a></p></li>'
        '<li id="fn3"><p>NOTE A<a href="#fnref3" class="footnote-back">back</a></p></li>'
        "</ol></section>"
    )
    out = reuse_footnotes(html)

    # the duplicate note (fn3 == fn1's "NOTE A") is dropped: exactly two <li> survive, renumbered
    assert out.count("<li id=") == 2
    assert out.count("NOTE A") == 1 and out.count("NOTE B") == 1
    assert '<li id="fn1"><p>NOTE A' in out and '<li id="fn2"><p>NOTE B' in out
    # both citations of the merged note now point to fn1 and display "1"
    assert out.count('href="#fn1" class="footnote-ref"') == 2
    assert '<a href="#fn3"' not in out  # the third reference was renumbered away
    # NOTE B's single citation keeps number 2
    assert (
        'href="#fn2" class="footnote-ref"' in out
        and out.count('href="#fn2" class="footnote-ref"') == 1
    )


def test_reuse_footnotes_is_a_noop_without_a_footnotes_section() -> None:
    plain = "<p>No footnotes here.</p>"
    assert reuse_footnotes(plain) == plain


# ------------------------------------------------------------------ manuscript assembly
def test_assemble_manuscript_prepends_the_front_matter_block() -> None:
    draft = (
        "<!-- Generated by `schelling paper-assemble` — DO NOT edit. -->\n\n"
        "# The Title\n\n## Abstract\n\nBody text.\n"
    )
    out = assemble_manuscript(draft, _fm())
    assert out.startswith("# The Title\n")  # banner dropped, title kept
    assert "**A. Author**  \n" in out
    assert "Somewhere · Correspondence: a@x.org · " in out
    assert "ORCID: [0009-0004-5391-4030](https://orcid.org/0009-0004-5391-4030)" in out
    assert "Preprint · 2026-01-01 · v9" in out
    assert "**Keywords:** one; two" in out
    assert "*changed things*" in out
    assert out.rstrip().endswith("Body text.")  # body verbatim after the block
    assert "## Abstract" in out


def test_assemble_manuscript_rejects_a_draft_without_an_h1() -> None:
    with pytest.raises(ValueError, match="H1 title"):
        assemble_manuscript("no title here\n\nbody\n", _fm())


# ------------------------------------------------------------------ front-matter config
def test_load_front_matter_reads_the_committed_repo_config() -> None:
    fm = load_front_matter(REPO / "paper" / "preprint" / "front-matter.toml")
    assert fm.author == "Hamza Gul Hassan"
    assert fm.orcid == "0009-0004-5391-4030"
    assert fm.dateline.endswith("v7") and fm.runhead.endswith("v7")
    assert "Bueno de Mesquita model" in fm.keywords


def test_load_front_matter_raises_on_a_missing_field(tmp_path: Path) -> None:
    cfg = tmp_path / "fm.toml"
    cfg.write_text('author = "A"\naffiliation = "B"\n')  # everything else missing
    with pytest.raises(ValueError, match="missing"):
        load_front_matter(cfg)


# ------------------------------------------------------------------ drift guard + figure inlining
def test_preprint_build_reproduces_the_committed_manuscript() -> None:
    """`schelling preprint build --md-only` must reproduce the committed manuscript.md byte-for-byte
    from the committed DRAFT.md + front matter — so command and artifact never drift."""
    draft = (REPO / "paper" / "DRAFT.md").read_text()
    fm = load_front_matter(REPO / "paper" / "preprint" / "front-matter.toml")
    rebuilt = assemble_manuscript(draft, fm)
    assert rebuilt == (REPO / "paper" / "preprint" / "manuscript.md").read_text()


def test_inline_figures_requires_exactly_one_reference(tmp_path: Path) -> None:
    (tmp_path / "fig_deu_error_histogram.svg").write_text("<svg/>")
    with pytest.raises(ValueError, match="expected exactly one reference"):
        inline_figures("no figure reference here", tmp_path)
