"""Assemble the SSRN preprint manuscript from the paper (Session 55, D55).

``paper/DRAFT.md`` -> ``paper/preprint/manuscript.md``: drop the ``paper-assemble`` banner comment
and prepend a title/author/contact/date/keywords block plus a one-line version note (the D43.0/D51.5
transform, now a first-class step). No prose is edited — the body is the assembled paper verbatim,
so DRAFT.md and the preprint always agree.
"""

from __future__ import annotations

from schelling.preprint.frontmatter import FrontMatter


def assemble_manuscript(draft_text: str, fm: FrontMatter) -> str:
    """Return the preprint manuscript markdown: ``draft_text`` (DRAFT.md) plus the front matter."""
    text = draft_text
    if text.lstrip().startswith("<!--"):  # drop the "Generated by paper-assemble" banner comment
        text = text.split("-->", 1)[1].lstrip("\n")
    title, rest = text.split("\n", 1)
    if not title.startswith("# "):
        raise ValueError(f"expected an H1 title as the first line of DRAFT.md, got: {title!r}")
    author_block = "\n".join(
        [
            "",
            f"**{fm.author}**  ",
            f"{fm.affiliation} · Correspondence: {fm.contact} · "
            f"ORCID: [{fm.orcid}](https://orcid.org/{fm.orcid})  ",
            fm.dateline,
            "",
            f"**Keywords:** {fm.keywords}",
            "",
            f"*{fm.version_note}*",
            "",
        ]
    )
    return title + "\n" + author_block + "\n" + rest.lstrip("\n")
